services:
  chatbot:
    container_name: camanchaca-chatbot
    build: .
    ports:
      - "8501:8501"
    env_file:
      - .env
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
            - .git/
            - .gitignore
            - __pycache__/
            - "*.pyc"
            - ".ipynb"
            - "*.md"
            - README.md
        - action: rebuild
          path: requirements.txt
